development:
  sessions:
    default:
      database: wayfaring_development
      hosts: 
        - localhost:27017

test:
  sessions:
    default:
      database: wayfaring_test
      hosts: 
        - localhost:27017

# set these environment variables on your prod server
